import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";

const eslintConfig = defineConfig([
  ...nextVitals,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `npm run test:coverage`.
    "coverage/**",
    // Never lint third-party code. eslint ignores the root node_modules by
    // default but not a nested one, which is how vendored codec .d.ts files
    // once failed the build.
    "**/node_modules/**",
    "**/vendor/**",
  ]),
]);

export default eslintConfig;
