/**
 * Fixtures for the browser engine tests.
 *
 * Everything is generated by sharp at run time so no binary is committed.
 * sharp is a FIXTURE TOOL here and nothing more — it never appears on the
 * client path under test, which is the whole point of this PR.
 *
 * These were once shared with a server-route suite that has been deleted along
 * with the routes. What that suite owned and this one needs — the File builder
 * below — moved here rather than being left behind an import into a directory
 * that no longer exists.
 */
import sharp from 'sharp';

/**
 * A File with an overridable reported size.
 *
 * The capability gate reads a file's declared type and `size` and never its
 * bytes, so the size-cap cases can be proved without allocating 20 MB of real
 * buffer. `Object.defineProperty` is how the override is done because `size` is
 * a getter on File and cannot be assigned.
 */
export function makeFile(bytes, { name = 'photo.jpg', type = 'image/jpeg', size } = {}) {
    const file = new File([bytes], name, { type });
    if (size !== undefined) {
        Object.defineProperty(file, 'size', { value: size, configurable: true });
    }
    return file;
}

/** The string the server suite looks for. Same marker, same question. */
export const EXIF_MARKER = 'RESIZO-EXIF-MARKER';

/**
 * A second marker, written into the GPS IFD. EXIF and GPS live in different
 * IFDs and a stripper can plausibly drop one and keep the other, so "no EXIF"
 * and "no location" are asserted separately.
 */
export const GPS_MARKER = 'RESIZO-GPS-MARKER';

const cache = new Map();

function memo(key, build) {
    if (!cache.has(key)) cache.set(key, build());
    return cache.get(key);
}

/**
 * A JPEG carrying both a text marker in IFD0 and a real GPS IFD — reference,
 * three latitude rationals, three longitude rationals and a datestamp holding
 * the second marker.
 *
 * libvips numbers the IFDs rather than naming them: IFD3 is the GPS IFD. A
 * `GPS:` key is silently dropped, which would have produced a fixture that
 * proved nothing.
 */
export function jpegWithExifAndGps({ width = 60, height = 40 } = {}) {
    return memo(`exif-gps:${width}x${height}`, () => sharp({
        create: { width, height, channels: 3, background: { r: 200, g: 40, b: 80 } },
    })
        .withExif({
            IFD0: { Copyright: EXIF_MARKER, Software: EXIF_MARKER },
            IFD3: {
                GPSLatitudeRef: 'N',
                GPSLatitude: '51/1 30/1 26/1',
                GPSLongitudeRef: 'W',
                GPSLongitude: '0/1 7/1 39/1',
                GPSDateStamp: GPS_MARKER,
            },
        })
        .jpeg()
        .toBuffer());
}

/**
 * Left half pure red, right half pure blue. Two flat blocks with one hard seam:
 * a resampler that swaps channels, mixes up the row stride or reads the buffer
 * as BGRA shows it immediately, where a gradient would hide it.
 */
export function splitRedBluePixels(width, height) {
    const pixels = Buffer.alloc(width * height * 3);
    for (let y = 0; y < height; y += 1) {
        for (let x = 0; x < width; x += 1) {
            const offset = (y * width + x) * 3;
            if (x < width / 2) pixels[offset] = 255;
            else pixels[offset + 2] = 255;
        }
    }
    return pixels;
}

export function splitRedBluePng({ width = 80, height = 40 } = {}) {
    return memo(`split-png:${width}x${height}`, () => sharp(splitRedBluePixels(width, height), {
        raw: { width, height, channels: 3 },
    }).png().toBuffer());
}

/**
 * The split image tagged with one of the eight EXIF Orientation values. The tag
 * says how a viewer must turn the stored pixels to display them the right way
 * up, so `width`x`height` on disk is `height`x`width` on screen for 5-8.
 *
 * sharp's `withExif` will not write the Orientation tag (it reports back as 1);
 * `withMetadata({ orientation })` does.
 *
 * A hard red/blue seam rather than a gradient because a seam is the only thing
 * that tells a 90 degree rotation apart from its mirror: dimensions alone
 * cannot, and orientations 5 and 6 produce the same shape.
 */
export function splitRedBlueJpegOriented({ width = 40, height = 20, orientation = 6 } = {}) {
    return memo(`split-oriented:${width}x${height}:${orientation}`, () => sharp(splitRedBluePixels(width, height), {
        raw: { width, height, channels: 3 },
    })
        .withMetadata({ orientation })
        .jpeg({ quality: 100, chromaSubsampling: '4:4:4' })
        .toBuffer());
}

/** The Orientation-6 case on its own — "rotate 90 degrees clockwise to display". */
export function splitRedBlueJpegRotated({ width = 40, height = 20 } = {}) {
    return splitRedBlueJpegOriented({ width, height, orientation: 6 });
}

/** The same picture with no EXIF block at all, as the untagged control. */
export function splitRedBlueJpegPlain({ width = 40, height = 20 } = {}) {
    return memo(`split-plain:${width}x${height}`, () => sharp(splitRedBluePixels(width, height), {
        raw: { width, height, channels: 3 },
    })
        .jpeg({ quality: 100, chromaSubsampling: '4:4:4' })
        .toBuffer());
}

/**
 * Deterministic pseudo-random RGB noise, as a JPEG.
 *
 * The one fixture that cannot be compressed. A flat colour is a few hundred
 * bytes at any quality, so it can never prove anything about a SIZE target —
 * every probe would fit. Noise costs roughly its own pixel count in bytes even
 * at quality 1, which is what makes an unreachable target reachable to test.
 *
 * The generator is a plain LCG rather than Math.random so the same fixture
 * comes out of every run and a size assertion cannot flake.
 */
export function noiseJpeg({ width = 400, height = 300, quality = 92, seed = 1 } = {}) {
    return memo(`noise-jpeg:${width}x${height}:${quality}:${seed}`, () => {
        const pixels = Buffer.alloc(width * height * 3);
        let state = seed >>> 0;
        for (let index = 0; index < pixels.length; index += 1) {
            state = (Math.imul(state, 1664525) + 1013904223) >>> 0;
            pixels[index] = (state >>> 16) & 0xFF;
        }
        return sharp(pixels, { raw: { width, height, channels: 3 } }).jpeg({ quality }).toBuffer();
    });
}

/** A half-transparent PNG, for the premultiply/alpha assertions. */
export function halfAlphaPng({ width = 40, height = 30 } = {}) {
    return memo(`alpha-png:${width}x${height}`, () => sharp({
        create: { width, height, channels: 4, background: { r: 10, g: 120, b: 200, alpha: 0.5 } },
    }).png().toBuffer());
}

/**
 * Builds an ImageData without going through a decoder, for the encode tests
 * that have nothing to decode. Requires installBrowserEnv() to have run.
 *
 * `paint(x, y)` returns [r, g, b, a].
 */
export function makeImageData(width, height, paint = () => [200, 40, 80, 255]) {
    const data = new Uint8ClampedArray(width * height * 4);
    for (let y = 0; y < height; y += 1) {
        for (let x = 0; x < width; x += 1) {
            const [r, g, b, a] = paint(x, y);
            const offset = (y * width + x) * 4;
            data[offset] = r;
            data[offset + 1] = g;
            data[offset + 2] = b;
            data[offset + 3] = a;
        }
    }
    return new ImageData(data, width, height);
}

/** A smooth gradient as ImageData: flat colour compresses identically at every quality. */
export function gradientImageData(width = 120, height = 120) {
    return makeImageData(width, height, (x, y) => [
        Math.floor((x * 255) / width),
        Math.floor((y * 255) / height),
        Math.floor(((x + y) * 255) / (width + height)),
        255,
    ]);
}
