/**
 * Fixtures for the browser engine tests.
 *
 * Everything is generated by sharp at run time so no binary is committed.
 * sharp is a FIXTURE TOOL here and nothing more — it never appears on the
 * client path under test, which is the whole point of this PR.
 *
 * These were once shared with a server-route suite that has been deleted along
 * with the routes. What that suite owned and this one needs — the File builder
 * below — moved here rather than being left behind an import into a directory
 * that no longer exists.
 */
import sharp from 'sharp';

/**
 * A File with an overridable reported size.
 *
 * The capability gate reads a file's declared type and `size` and never its
 * bytes, so the size-cap cases can be proved without allocating 20 MB of real
 * buffer. `Object.defineProperty` is how the override is done because `size` is
 * a getter on File and cannot be assigned.
 */
export function makeFile(bytes, { name = 'photo.jpg', type = 'image/jpeg', size } = {}) {
    const file = new File([bytes], name, { type });
    if (size !== undefined) {
        Object.defineProperty(file, 'size', { value: size, configurable: true });
    }
    return file;
}

/** The string the server suite looks for. Same marker, same question. */
export const EXIF_MARKER = 'RESIZO-EXIF-MARKER';

/**
 * A second marker, written into the GPS IFD. EXIF and GPS live in different
 * IFDs and a stripper can plausibly drop one and keep the other, so "no EXIF"
 * and "no location" are asserted separately.
 */
export const GPS_MARKER = 'RESIZO-GPS-MARKER';

/**
 * A second pair, for the image that hides in a TRAILER.
 *
 * A phone does not stop writing at the end of the primary picture: Apple appends
 * MPF secondary images for an HDR gain map, each with its own APP1 Exif and GPS
 * block, and Samsung and Google append a Motion Photo video. Those bytes sit
 * AFTER the primary image's EOI and carry their own copy of where the photo was
 * taken. Distinct markers so a test can say which of the two images a surviving
 * coordinate came from.
 */
export const TRAILER_EXIF_MARKER = 'RESIZO-TRAILER-EXIF';
export const TRAILER_GPS_MARKER = 'RESIZO-TRAILER-GPS';

const cache = new Map();

function memo(key, build) {
    if (!cache.has(key)) cache.set(key, build());
    return cache.get(key);
}

/**
 * A JPEG carrying both a text marker in IFD0 and a real GPS IFD — reference,
 * three latitude rationals, three longitude rationals and a datestamp holding
 * the second marker.
 *
 * libvips numbers the IFDs rather than naming them: IFD3 is the GPS IFD. A
 * `GPS:` key is silently dropped, which would have produced a fixture that
 * proved nothing.
 */
export function jpegWithExifAndGps({
    width = 60,
    height = 40,
    exifMarker = EXIF_MARKER,
    gpsMarker = GPS_MARKER,
} = {}) {
    return memo(`exif-gps:${width}x${height}:${exifMarker}:${gpsMarker}`, () => sharp({
        create: { width, height, channels: 3, background: { r: 200, g: 40, b: 80 } },
    })
        .withExif({
            IFD0: { Copyright: exifMarker, Software: exifMarker },
            IFD3: {
                GPSLatitudeRef: 'N',
                GPSLatitude: '51/1 30/1 26/1',
                GPSLongitudeRef: 'W',
                GPSLongitude: '0/1 7/1 39/1',
                GPSDateStamp: gpsMarker,
            },
        })
        .jpeg()
        .toBuffer());
}

/**
 * Left half pure red, right half pure blue. Two flat blocks with one hard seam:
 * a resampler that swaps channels, mixes up the row stride or reads the buffer
 * as BGRA shows it immediately, where a gradient would hide it.
 */
export function splitRedBluePixels(width, height) {
    const pixels = Buffer.alloc(width * height * 3);
    for (let y = 0; y < height; y += 1) {
        for (let x = 0; x < width; x += 1) {
            const offset = (y * width + x) * 3;
            if (x < width / 2) pixels[offset] = 255;
            else pixels[offset + 2] = 255;
        }
    }
    return pixels;
}

export function splitRedBluePng({ width = 80, height = 40 } = {}) {
    return memo(`split-png:${width}x${height}`, () => sharp(splitRedBluePixels(width, height), {
        raw: { width, height, channels: 3 },
    }).png().toBuffer());
}

/**
 * The split image tagged with one of the eight EXIF Orientation values. The tag
 * says how a viewer must turn the stored pixels to display them the right way
 * up, so `width`x`height` on disk is `height`x`width` on screen for 5-8.
 *
 * sharp's `withExif` will not write the Orientation tag (it reports back as 1);
 * `withMetadata({ orientation })` does.
 *
 * A hard red/blue seam rather than a gradient because a seam is the only thing
 * that tells a 90 degree rotation apart from its mirror: dimensions alone
 * cannot, and orientations 5 and 6 produce the same shape.
 */
export function splitRedBlueJpegOriented({ width = 40, height = 20, orientation = 6 } = {}) {
    return memo(`split-oriented:${width}x${height}:${orientation}`, () => sharp(splitRedBluePixels(width, height), {
        raw: { width, height, channels: 3 },
    })
        .withMetadata({ orientation })
        .jpeg({ quality: 100, chromaSubsampling: '4:4:4' })
        .toBuffer());
}

/** The Orientation-6 case on its own — "rotate 90 degrees clockwise to display". */
export function splitRedBlueJpegRotated({ width = 40, height = 20 } = {}) {
    return splitRedBlueJpegOriented({ width, height, orientation: 6 });
}

/** The same picture with no EXIF block at all, as the untagged control. */
export function splitRedBlueJpegPlain({ width = 40, height = 20 } = {}) {
    return memo(`split-plain:${width}x${height}`, () => sharp(splitRedBluePixels(width, height), {
        raw: { width, height, channels: 3 },
    })
        .jpeg({ quality: 100, chromaSubsampling: '4:4:4' })
        .toBuffer());
}

/**
 * Deterministic pseudo-random RGB noise, as a JPEG.
 *
 * The one fixture that cannot be compressed. A flat colour is a few hundred
 * bytes at any quality, so it can never prove anything about a SIZE target —
 * every probe would fit. Noise costs roughly its own pixel count in bytes even
 * at quality 1, which is what makes an unreachable target reachable to test.
 *
 * The generator is a plain LCG rather than Math.random so the same fixture
 * comes out of every run and a size assertion cannot flake.
 */
export function noiseJpeg({ width = 400, height = 300, quality = 92, seed = 1 } = {}) {
    return memo(`noise-jpeg:${width}x${height}:${quality}:${seed}`, () => {
        const pixels = Buffer.alloc(width * height * 3);
        let state = seed >>> 0;
        for (let index = 0; index < pixels.length; index += 1) {
            state = (Math.imul(state, 1664525) + 1013904223) >>> 0;
            pixels[index] = (state >>> 16) & 0xFF;
        }
        return sharp(pixels, { raw: { width, height, channels: 3 } }).jpeg({ quality }).toBuffer();
    });
}

/**
 * A real HEIF container, optionally lying in its `ispe` box about how big the
 * picture is.
 *
 * WHAT THIS IS. sharp's libvips can write an ISOBMFF/HEIF file, but only with
 * AV1 payloads (the prebuilt binary carries no HEVC encoder and no HEVC encoder
 * exists to build against here). So the container, the `meta` box, the item
 * table and the `ispe` box are all genuine and are parsed by the real libheif —
 * which is the whole surface this fixture exists to exercise, because the
 * declared dimensions come out of `ispe` and nothing else.
 *
 * WHAT IT IS NOT. libheif-js ships no AV1 decoder, so the PIXELS cannot be
 * decoded from it in Node. Every assertion made with this fixture is therefore
 * about what happens BEFORE `display()` — which is exactly where the memory gate
 * has to live.
 *
 * The major brand is rewritten to 'mif1' because that is what makes
 * sniffImageType call it a HEIC rather than an AVIF, and 'mif1' is a brand real
 * HEIF files carry (sharp already lists it among this file's compatible brands).
 *
 * `declaredWidth`/`declaredHeight` overwrite the two big-endian words inside
 * `ispe`. That is precisely the attacker-controlled number: libheif reports it
 * from `heif_image_handle_get_width` without decoding anything, and the old code
 * multiplied it out into a buffer.
 */
export function heifDeclaring({
    width = 64,
    height = 48,
    declaredWidth = null,
    declaredHeight = null,
} = {}) {
    return memo(`heif:${width}x${height}:${declaredWidth}x${declaredHeight}`, async () => {
        const encoded = await sharp({
            create: { width, height, channels: 3, background: { r: 200, g: 40, b: 80 } },
        }).heif({ compression: 'av1', quality: 50 }).toBuffer();

        const bytes = Buffer.from(encoded);
        bytes.write('mif1', 8, 'latin1');

        const ispe = bytes.indexOf(Buffer.from('ispe', 'latin1'));
        if (ispe === -1) throw new Error('fixture: no ispe box in the HEIF container');

        if (declaredWidth !== null) bytes.writeUInt32BE(declaredWidth, ispe + 8);
        if (declaredHeight !== null) bytes.writeUInt32BE(declaredHeight, ispe + 12);

        return bytes;
    });
}

/** A half-transparent PNG, for the premultiply/alpha assertions. */
export function halfAlphaPng({ width = 40, height = 30 } = {}) {
    return memo(`alpha-png:${width}x${height}`, () => sharp({
        create: { width, height, channels: 4, background: { r: 10, g: 120, b: 200, alpha: 0.5 } },
    }).png().toBuffer());
}

/**
 * Builds an ImageData without going through a decoder, for the encode tests
 * that have nothing to decode. Requires installBrowserEnv() to have run.
 *
 * `paint(x, y)` returns [r, g, b, a].
 */
export function makeImageData(width, height, paint = () => [200, 40, 80, 255]) {
    const data = new Uint8ClampedArray(width * height * 4);
    for (let y = 0; y < height; y += 1) {
        for (let x = 0; x < width; x += 1) {
            const [r, g, b, a] = paint(x, y);
            const offset = (y * width + x) * 4;
            data[offset] = r;
            data[offset + 1] = g;
            data[offset + 2] = b;
            data[offset + 3] = a;
        }
    }
    return new ImageData(data, width, height);
}

/** A smooth gradient as ImageData: flat colour compresses identically at every quality. */
export function gradientImageData(width = 120, height = 120) {
    return makeImageData(width, height, (x, y) => [
        Math.floor((x * 255) / width),
        Math.floor((y * 255) / height),
        Math.floor(((x + y) * 255) / (width + height)),
        255,
    ]);
}

/**
 * A signature-shaped PNG: a wide, short, mostly TRANSPARENT sheet with a solid
 * block of ink across the middle.
 *
 * The shape is the point. A scanned signature is a banner — 800x300 here — and
 * the box a form asks for almost never has the same ratio, which is what makes
 * "fit inside", "fill and crop" and "stretch" three visibly different answers
 * rather than three names for one resize.
 *
 * The transparency is the other point. It is what a PNG signature is FOR, and
 * it is the difference between the two output formats: PNG has to keep it, and
 * JPEG has to fill it with something. The corners are far from the ink so a
 * corner pixel can be read back through a lossy encoder without measuring the
 * DCT instead of the fill.
 */
export function signaturePng({ width = 800, height = 300 } = {}) {
    return memo(`signature-png:${width}x${height}`, () => {
        const inkWidth = Math.round(width / 2);
        const inkHeight = Math.round(height / 3);

        return sharp({
            create: { width, height, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } },
        })
            .composite([{
                input: {
                    create: {
                        width: inkWidth,
                        height: inkHeight,
                        channels: 4,
                        background: { r: 12, g: 24, b: 48, alpha: 1 },
                    },
                },
                left: Math.round((width - inkWidth) / 2),
                top: Math.round((height - inkHeight) / 2),
            }])
            .png()
            .toBuffer();
    });
}
