/**
 * Fixtures for the browser engine tests.
 *
 * Everything is generated by sharp at run time so no binary is committed.
 * sharp is a FIXTURE TOOL here and nothing more — it never appears on the
 * client path under test, which is the whole point of this PR.
 *
 * The shared images (plain JPEG/PNG/WebP, gradients, the hostile byte strings)
 * are reused from tests/api/helpers/fixtures.js rather than rebuilt, so the
 * browser engine is judged against the same pictures the server was.
 */
import sharp from 'sharp';

/** The string the server suite looks for. Same marker, same question. */
export const EXIF_MARKER = 'RESIZO-EXIF-MARKER';

/**
 * A second marker, written into the GPS IFD. EXIF and GPS live in different
 * IFDs and a stripper can plausibly drop one and keep the other, so "no EXIF"
 * and "no location" are asserted separately.
 */
export const GPS_MARKER = 'RESIZO-GPS-MARKER';

const cache = new Map();

function memo(key, build) {
    if (!cache.has(key)) cache.set(key, build());
    return cache.get(key);
}

/**
 * A JPEG carrying both a text marker in IFD0 and a real GPS IFD — reference,
 * three latitude rationals, three longitude rationals and a datestamp holding
 * the second marker.
 *
 * libvips numbers the IFDs rather than naming them: IFD3 is the GPS IFD. A
 * `GPS:` key is silently dropped, which would have produced a fixture that
 * proved nothing.
 */
export function jpegWithExifAndGps({ width = 60, height = 40 } = {}) {
    return memo(`exif-gps:${width}x${height}`, () => sharp({
        create: { width, height, channels: 3, background: { r: 200, g: 40, b: 80 } },
    })
        .withExif({
            IFD0: { Copyright: EXIF_MARKER, Software: EXIF_MARKER },
            IFD3: {
                GPSLatitudeRef: 'N',
                GPSLatitude: '51/1 30/1 26/1',
                GPSLongitudeRef: 'W',
                GPSLongitude: '0/1 7/1 39/1',
                GPSDateStamp: GPS_MARKER,
            },
        })
        .jpeg()
        .toBuffer());
}

/**
 * Left half pure red, right half pure blue. Two flat blocks with one hard seam:
 * a resampler that swaps channels, mixes up the row stride or reads the buffer
 * as BGRA shows it immediately, where a gradient would hide it.
 */
export function splitRedBluePixels(width, height) {
    const pixels = Buffer.alloc(width * height * 3);
    for (let y = 0; y < height; y += 1) {
        for (let x = 0; x < width; x += 1) {
            const offset = (y * width + x) * 3;
            if (x < width / 2) pixels[offset] = 255;
            else pixels[offset + 2] = 255;
        }
    }
    return pixels;
}

export function splitRedBluePng({ width = 80, height = 40 } = {}) {
    return memo(`split-png:${width}x${height}`, () => sharp(splitRedBluePixels(width, height), {
        raw: { width, height, channels: 3 },
    }).png().toBuffer());
}

/**
 * The same split image tagged EXIF Orientation 6 — "rotate 90 degrees clockwise
 * to display". A viewer honouring the tag shows it upright at height x width.
 *
 * sharp's `withExif` will not write the Orientation tag (it reports back as 1);
 * `withMetadata({ orientation })` does.
 */
export function splitRedBlueJpegRotated({ width = 40, height = 20 } = {}) {
    return memo(`split-rotated:${width}x${height}`, () => sharp(splitRedBluePixels(width, height), {
        raw: { width, height, channels: 3 },
    })
        .withMetadata({ orientation: 6 })
        .jpeg()
        .toBuffer());
}

/** A half-transparent PNG, for the premultiply/alpha assertions. */
export function halfAlphaPng({ width = 40, height = 30 } = {}) {
    return memo(`alpha-png:${width}x${height}`, () => sharp({
        create: { width, height, channels: 4, background: { r: 10, g: 120, b: 200, alpha: 0.5 } },
    }).png().toBuffer());
}

/**
 * Builds an ImageData without going through a decoder, for the encode tests
 * that have nothing to decode. Requires installBrowserEnv() to have run.
 *
 * `paint(x, y)` returns [r, g, b, a].
 */
export function makeImageData(width, height, paint = () => [200, 40, 80, 255]) {
    const data = new Uint8ClampedArray(width * height * 4);
    for (let y = 0; y < height; y += 1) {
        for (let x = 0; x < width; x += 1) {
            const [r, g, b, a] = paint(x, y);
            const offset = (y * width + x) * 4;
            data[offset] = r;
            data[offset + 1] = g;
            data[offset + 2] = b;
            data[offset + 3] = a;
        }
    }
    return new ImageData(data, width, height);
}

/** A smooth gradient as ImageData: flat colour compresses identically at every quality. */
export function gradientImageData(width = 120, height = 120) {
    return makeImageData(width, height, (x, y) => [
        Math.floor((x * 255) / width),
        Math.floor((y * 255) / height),
        Math.floor(((x + y) * 255) / (width + height)),
        255,
    ]);
}
