'use client';

/**
 * The resize workspace: one image, or up to twenty.
 *
 * Lifted out of the 1334-line homepage monolith, where it also carried the
 * nav, the footer, the reviews and two modals, and where the single and bulk
 * panels shared one `isDragging` and one `errorMsg` — so dragging over one
 * zone lit up the other and an error raised in one tab appeared in both. The
 * two panels now own separate upload hooks, which is what actually fixes that.
 *
 * Both hooks are mounted at all times even though only one panel renders:
 * switching tabs must not silently throw away a batch someone just queued up.
 *
 * Both panels do their work in this tab and nothing else. The single one goes
 * through useLocalProcess, exactly as /crop does; the bulk one goes through
 * useBulkResize, which puts the same capability gate in front of each file in
 * turn.
 *
 * The measured source dimensions are passed on every submit. They are not a
 * convenience: they are what lets the memory gate cost the job BEFORE anything
 * decodes, which on iOS is the difference between a sentence a person can read
 * and a tab that silently dies holding their photo.
 */
import { useCallback, useEffect, useMemo, useState } from 'react';

import ResultPanel from '@/components/tools/ResultPanel';
import ToolShell, { ToolAction } from '@/components/tools/ToolShell';
import Dropzone from '@/components/ui/Dropzone';
import FilePreviewCard from '@/components/ui/FilePreviewCard';
import {
    ALLOWED_OUTPUT_FORMATS,
    MAX_BULK_FILES,
    MAX_DIMENSION,
    MAX_SCALE_PERCENT,
    RESIZE_INPUT_FORMATS,
} from '@/lib/constants';
import { formatSavings, savingsPercent } from '@/lib/hooks/submit-helpers';
import { formatLabel } from '@/lib/hooks/upload-helpers';
import { useBulkResize } from '@/lib/hooks/useBulkResize';
import { useImageUpload } from '@/lib/hooks/useImageUpload';
import { useLocalProcess } from '@/lib/hooks/useLocalProcess';
import {
    deriveHeight,
    deriveWidth,
    explicitTargetDimensions,
    parsePositiveInt,
    parseScale,
    scaleDimensions,
} from '@/lib/image/dimensions';
import { takePendingFiles } from '@/lib/pending-files';

import { BulkSettings, SingleSettings } from './ResizeSettings';

/**
 * Bundled images so a visitor can see what comes out before handing over a
 * photo of their own. Generated by scripts/generate-samples.js — three aspect
 * ratios, because respecting one is the first thing a resizer has to prove.
 */
const SAMPLES = [
    { src: '/samples/landscape-1600x1067.jpg', name: 'landscape-1600x1067.jpg', label: 'Landscape', dimensions: '1600×1067' },
    { src: '/samples/portrait-1080x1440.jpg', name: 'portrait-1080x1440.jpg', label: 'Portrait', dimensions: '1080×1440' },
    { src: '/samples/square-1200x1200.jpg', name: 'square-1200x1200.jpg', label: 'Square', dimensions: '1200×1200' },
];

const DIMENSION_ERROR = `Width and height have to be whole numbers of pixels, up to ${MAX_DIMENSION}.`;
const SCALE_ERROR = `Scale has to be a number above 0 and no more than ${MAX_SCALE_PERCENT}.`;

function numberOrNull(value) {
    const parsed = Number(value);
    return Number.isFinite(parsed) && parsed > 0 ? Math.round(parsed) : null;
}

/**
 * 'original' is a UI convenience, not a server format: it resolves to a real
 * encoder here rather than being rewritten by the route's own fallback. Every
 * accepted input is now also an encodable output — GIF was the one that was
 * not — so the jpeg branch is a backstop, not a path a real file takes.
 */
function resolveOutputFormat(choice, sourceFormat) {
    if (choice && choice !== 'original') return choice;
    return ALLOWED_OUTPUT_FORMATS.includes(sourceFormat) ? sourceFormat : 'jpeg';
}

/** The same strict parsers lib/image/dimensions.js uses, so the form and the engine agree. */
function validateTarget(width, height, { requireOne = false } = {}) {
    const parsedWidth = parsePositiveInt(width, { max: MAX_DIMENSION });
    const parsedHeight = parsePositiveInt(height, { max: MAX_DIMENSION });

    if ((!parsedWidth.ok && !parsedWidth.absent) || (!parsedHeight.ok && !parsedHeight.absent)) {
        return { error: DIMENSION_ERROR };
    }
    if (requireOne && parsedWidth.absent && parsedHeight.absent) {
        return { error: 'Enter a width, a height, or both — or switch to Percent.' };
    }

    return {
        width: parsedWidth.ok ? parsedWidth.value : null,
        height: parsedHeight.ok ? parsedHeight.value : null,
    };
}

/**
 * The output size a submit is heading for, for the memory gate.
 *
 * Nulls when it cannot be worked out — no measured source, or a target the
 * engine would refuse anyway. The gate then costs a same-size job, which is the
 * honest estimate with nothing better to go on, and the refusal still arrives
 * from the engine in its own words.
 */
function targetForGate(entry, { width = null, height = null, scalePercent = null }) {
    if (!entry?.width || !entry?.height) return { width: null, height: null };

    const resolved = scalePercent !== null
        ? scaleDimensions(entry.width, entry.height, scalePercent)
        : explicitTargetDimensions(entry.width, entry.height, { width, height });

    return resolved.ok ? { width: resolved.width, height: resolved.height } : { width: null, height: null };
}

function describeTarget(entry, target) {
    const format = formatLabel(resolveOutputFormat(target.format, entry.format));

    if (target.width && target.height) return `${target.width}×${target.height} · ${format}`;
    if (target.width) return `${target.width}×auto · ${format}`;
    if (target.height) return `auto×${target.height} · ${format}`;
    if (Number.isFinite(entry.width) && Number.isFinite(entry.height)) {
        return `${entry.width}×${entry.height} · ${format}`;
    }
    return `Unchanged size · ${format}`;
}

/** The live status token for one file in a running batch. */
function bulkStatusLabel(row) {
    if (row.status === 'processing') return 'Resizing…';
    if (row.status === 'failed') return 'Failed';
    if (row.status === 'done') {
        return formatSavings(savingsPercent(row.originalBytes, row.resultBytes)) ?? 'Done';
    }
    return 'Waiting';
}

function SampleRow({ onPick, disabled }) {
    return (
        <div className="flex flex-col items-center gap-2">
            <p className="text-micro text-ink-muted">No image to hand? Try one of these.</p>
            <div className="flex flex-wrap justify-center gap-2">
                {SAMPLES.map((sample) => (
                    <button
                        key={sample.src}
                        type="button"
                        disabled={disabled}
                        onClick={() => onPick(sample)}
                        className="flex items-baseline gap-2 rounded-button border border-line bg-surface-raised px-3 py-1.5 transition-colors duration-120 ease-snap hover:bg-surface-sunken disabled:opacity-60"
                    >
                        <span className="text-ui text-ink">{sample.label}</span>
                        <span className="font-data text-micro text-ink-muted">{sample.dimensions}</span>
                    </button>
                ))}
            </div>
        </div>
    );
}

export default function ResizeTool({
    title = 'Resize an Image Online',
    intro = 'Exact pixels, a percentage, or a platform size — then drop your file. It is resized on your device, not uploaded.',
    breadcrumb,
    children,
}) {
    const [mode, setMode] = useState('single');
    const [formError, setFormError] = useState(null);

    // Single
    const [sizeMode, setSizeMode] = useState('pixels');
    const [presetId, setPresetId] = useState(null);
    const [width, setWidth] = useState('');
    const [height, setHeight] = useState('');
    const [lockRatio, setLockRatio] = useState(true);
    const [scale, setScale] = useState('50');
    const [format, setFormat] = useState('original');
    const [resultUrl, setResultUrl] = useState(null);
    const [resultSize, setResultSize] = useState(null);

    // Bulk
    const [bulkWidth, setBulkWidth] = useState('');
    const [bulkHeight, setBulkHeight] = useState('');
    const [bulkFormat, setBulkFormat] = useState('original');

    const singleUpload = useImageUpload({ accept: RESIZE_INPUT_FORMATS });
    const bulkUpload = useImageUpload({
        accept: RESIZE_INPUT_FORMATS,
        multiple: true,
        maxFiles: MAX_BULK_FILES,
    });

    const singleSubmit = useLocalProcess({ op: 'resize' });
    const bulkResize = useBulkResize({ op: 'resize' });

    const source = singleUpload.file;
    const hasSourceSize = Boolean(source?.width && source?.height);

    /* ---------------------------------------------------------------- *
     * Single
     * ---------------------------------------------------------------- */

    // The hook results are in the dependency arrays below as whole objects,
    // which is what exhaustive-deps demands for a `hook.method()` call. Their
    // members are all useCallback-stable, so the only cost is that a handler
    // is re-created each render — never a re-run of anything expensive.
    const handleSingleFiles = useCallback(async (files) => {
        setFormError(null);
        singleSubmit.reset();

        const [entry] = await singleUpload.selectFiles(files);
        if (!entry) return;

        // A preset already chosen is an explicit target; only an unconfigured
        // panel adopts the source dimensions.
        if (!presetId) {
            setWidth(entry.width ? String(entry.width) : '');
            setHeight(entry.height ? String(entry.height) : '');
        }
    }, [presetId, singleSubmit, singleUpload]);

    // The homepage hero takes the first drop and hands the file over as the
    // router transitions, so /resize opens with it already loaded. Empty on a
    // direct visit, and emptied by the read, so it cannot fire twice.
    useEffect(() => {
        const handed = takePendingFiles();
        if (handed.length > 0) void handleSingleFiles(handed);
    }, [handleSingleFiles]);

    // /resize#bulk is the registry href for the bulk tool, so the anchor has
    // to actually open that panel — on first paint, and again if someone
    // follows the link while already on this page, which does not remount.
    useEffect(() => {
        const sync = () => {
            if (window.location.hash === '#bulk') setMode('bulk');
        };

        sync();
        window.addEventListener('hashchange', sync);
        return () => window.removeEventListener('hashchange', sync);
    }, []);

    const singleResult = singleSubmit.result;

    // The output is measured, not predicted: with both sides set the route
    // scales to fill and trims, so a calculated number could be a lie.
    useEffect(() => {
        const blob = singleResult?.blob;
        if (!blob) {
            setResultUrl(null);
            setResultSize(null);
            return undefined;
        }

        const url = URL.createObjectURL(blob);
        setResultUrl(url);
        setResultSize(null);

        let cancelled = false;
        const probe = new window.Image();
        probe.onload = () => {
            if (!cancelled) setResultSize({ width: probe.naturalWidth, height: probe.naturalHeight });
        };
        probe.src = url;

        return () => {
            cancelled = true;
            URL.revokeObjectURL(url);
        };
    }, [singleResult]);

    // The ratio lock derives through the shared helpers rather than its own
    // arithmetic. It used to compute `round(width * (h / w))`, which is not the
    // same floating-point expression as the `round(h * (width / w))` the route
    // and the engine both use, so the number in the field could be a pixel off
    // what actually came back.
    const handleWidthChange = useCallback((value) => {
        setPresetId(null);
        setWidth(value);
        if (!lockRatio || !hasSourceSize) return;
        const next = numberOrNull(value);
        setHeight(next ? String(deriveHeight(source.width, source.height, next)) : '');
    }, [hasSourceSize, lockRatio, source]);

    const handleHeightChange = useCallback((value) => {
        setPresetId(null);
        setHeight(value);
        if (!lockRatio || !hasSourceSize) return;
        const next = numberOrNull(value);
        setWidth(next ? String(deriveWidth(source.width, source.height, next)) : '');
    }, [hasSourceSize, lockRatio, source]);

    const handlePresetSelect = useCallback((preset) => {
        if (!preset) {
            setPresetId(null);
            setWidth(source?.width ? String(source.width) : '');
            setHeight(source?.height ? String(source.height) : '');
            return;
        }

        setPresetId(preset.id);
        setSizeMode('pixels');
        // A platform size fixes both sides, so the ratio lock would immediately
        // overwrite one of them.
        setLockRatio(false);
        setWidth(String(preset.width));
        setHeight(String(preset.height));
    }, [source]);

    const loadSample = useCallback(async (sample) => {
        try {
            const response = await fetch(sample.src);
            if (!response.ok) throw new Error('sample unavailable');
            const blob = await response.blob();
            await handleSingleFiles([new File([blob], sample.name, { type: 'image/jpeg' })]);
        } catch {
            singleUpload.setError('That sample could not be loaded. Try again, or pick a file of your own.');
        }
    }, [handleSingleFiles, singleUpload]);

    const handleSingleSubmit = useCallback(async () => {
        if (!source) {
            setFormError('Choose an image first.');
            return;
        }

        const formData = new FormData();
        formData.append('file', source.file);
        formData.append('format', resolveOutputFormat(format, source.format));

        const requested = { width: null, height: null, scalePercent: null };

        if (sizeMode === 'pixels') {
            const target = validateTarget(width, height, { requireOne: true });
            if (target.error) {
                setFormError(target.error);
                return;
            }
            if (target.width) formData.append('width', String(target.width));
            if (target.height) formData.append('height', String(target.height));
            requested.width = target.width;
            requested.height = target.height;
        } else {
            const parsed = parseScale(scale);
            if (!parsed.ok) {
                setFormError(SCALE_ERROR);
                return;
            }
            formData.append('scale', String(parsed.value));
            requested.scalePercent = parsed.value;
        }

        setFormError(null);

        const output = targetForGate(source, requested);

        // The dimensions travel with the job, not just the fields. Without them
        // the memory gate cannot run until a decode has already allocated —
        // which is the one thing it exists to get in front of.
        await singleSubmit.submit(formData, {
            originalBytes: source.size,
            sourceWidth: source.width ?? null,
            sourceHeight: source.height ?? null,
            targetWidth: output.width,
            targetHeight: output.height,
        });
    }, [format, height, scale, singleSubmit, sizeMode, source, width]);

    const resetSingle = useCallback(() => {
        singleSubmit.reset();
        singleUpload.clear();
        setPresetId(null);
        setWidth('');
        setHeight('');
        setFormError(null);
    }, [singleSubmit, singleUpload]);

    const outputPreview = useMemo(() => {
        if (!source?.width || !source?.height) return null;

        if (sizeMode === 'percent') {
            const percent = Number(scale);
            if (!Number.isFinite(percent) || percent <= 0) return null;
            return `${Math.max(1, Math.round(source.width * (percent / 100)))}×${Math.max(1, Math.round(source.height * (percent / 100)))} px`;
        }

        const targetWidth = numberOrNull(width);
        const targetHeight = numberOrNull(height);

        if (targetWidth && targetHeight) return `${targetWidth}×${targetHeight} px`;
        if (targetWidth) return `${targetWidth}×${deriveHeight(source.width, source.height, targetWidth)} px`;
        if (targetHeight) return `${deriveWidth(source.width, source.height, targetHeight)}×${targetHeight} px`;
        return null;
    }, [height, scale, sizeMode, source, width]);

    /* ---------------------------------------------------------------- *
     * Bulk
     * ---------------------------------------------------------------- */

    const bulkFiles = bulkUpload.files;
    const selected = useMemo(() => bulkFiles.filter((entry) => entry.selected), [bulkFiles]);
    const allSelected = bulkFiles.length > 0 && selected.length === bulkFiles.length;

    const batchTarget = useMemo(() => ({
        width: numberOrNull(bulkWidth),
        height: numberOrNull(bulkHeight),
        format: bulkFormat,
    }), [bulkFormat, bulkHeight, bulkWidth]);

    const handleBulkFiles = useCallback(async (files) => {
        setFormError(null);
        bulkResize.reset();
        await bulkUpload.selectFiles(files);
    }, [bulkResize, bulkUpload]);

    const handleToggleAll = useCallback(() => {
        const next = !allSelected;
        for (const entry of bulkFiles) bulkUpload.updateFile(entry.id, { selected: next });
    }, [allSelected, bulkFiles, bulkUpload]);

    const handleApplyToSelected = useCallback(() => {
        const target = validateTarget(bulkWidth, bulkHeight);
        if (target.error) {
            setFormError(target.error);
            return;
        }

        setFormError(null);
        for (const entry of bulkFiles) {
            if (!entry.selected) continue;
            bulkUpload.updateFile(entry.id, {
                config: { width: target.width, height: target.height, format: bulkFormat },
            });
        }
    }, [bulkFiles, bulkFormat, bulkHeight, bulkUpload, bulkWidth]);

    const handleBulkSubmit = useCallback(async () => {
        const included = bulkFiles.filter((entry) => entry.selected);

        if (included.length === 0) {
            setFormError('Tick at least one image to resize.');
            return;
        }

        const fallback = validateTarget(bulkWidth, bulkHeight);
        if (fallback.error) {
            setFormError(fallback.error);
            return;
        }

        setFormError(null);

        // One file at a time. 'original' resolves to a concrete encoder here —
        // the engine only encodes JPEG/PNG/WebP — so nothing downstream is left
        // guessing what "same as the input" meant. The measured dimensions ride
        // along so the memory gate can cost each file before it decodes.
        const items = included.map((entry) => {
            const target = entry.config ?? { width: fallback.width, height: fallback.height, format: bulkFormat };
            const fields = { format: resolveOutputFormat(target.format, entry.format) };
            if (target.width) fields.width = String(target.width);
            if (target.height) fields.height = String(target.height);
            return {
                id: entry.id,
                name: entry.name,
                file: entry.file,
                fields,
                sourceWidth: entry.width ?? null,
                sourceHeight: entry.height ?? null,
            };
        });

        await bulkResize.run(items);
    }, [bulkFiles, bulkFormat, bulkHeight, bulkResize, bulkWidth]);

    const resetBulk = useCallback(() => {
        bulkResize.reset();
        bulkUpload.clear();
        setFormError(null);
    }, [bulkResize, bulkUpload]);

    const bulkProgressRows = bulkResize.progressRows;
    const bulkFailures = useMemo(
        () => bulkProgressRows.filter((row) => row.status === 'failed'),
        [bulkProgressRows],
    );

    /* ---------------------------------------------------------------- *
     * Render
     * ---------------------------------------------------------------- */

    const isSingle = mode === 'single';
    const activeError = isSingle ? singleSubmit.error : bulkResize.error;

    const changeMode = useCallback((next) => {
        setMode(next);
        setFormError(null);
    }, []);

    const settings = (
        <>
            {isSingle ? (
                <SingleSettings
                    mode={mode}
                    onModeChange={changeMode}
                    sizeMode={sizeMode}
                    onSizeModeChange={setSizeMode}
                    presetId={presetId}
                    onPresetSelect={handlePresetSelect}
                    width={width}
                    height={height}
                    onWidthChange={handleWidthChange}
                    onHeightChange={handleHeightChange}
                    lockRatio={lockRatio}
                    onLockRatioChange={setLockRatio}
                    scale={scale}
                    onScaleChange={setScale}
                    format={format}
                    onFormatChange={setFormat}
                    sourceFormat={source?.format ?? null}
                    outputPreview={outputPreview}
                />
            ) : (
                <BulkSettings
                    mode={mode}
                    onModeChange={changeMode}
                    width={bulkWidth}
                    height={bulkHeight}
                    onWidthChange={setBulkWidth}
                    onHeightChange={setBulkHeight}
                    format={bulkFormat}
                    onFormatChange={setBulkFormat}
                    selectedCount={selected.length}
                    totalCount={bulkFiles.length}
                    allSelected={allSelected}
                    onToggleAll={handleToggleAll}
                    onApplyToSelected={handleApplyToSelected}
                />
            )}
        </>
    );

    const singlePanel = (
        <Dropzone
            id="resize-file"
            label={source ? 'Drop another image to replace this one' : 'Drop an image here'}
            browseLabel={source ? 'Replace image' : 'Choose an image'}
            constraints={singleUpload.constraints}
            accept={singleUpload.accept}
            state={singleUpload.state}
            reason={singleUpload.error}
            onFiles={handleSingleFiles}
            disabled={singleSubmit.isProcessing}
        >
            <div className="w-full max-w-lg">
                {source ? (
                    <FilePreviewCard
                        name={source.name}
                        size={source.size}
                        format={source.format}
                        width={source.width}
                        height={source.height}
                        previewUrl={source.previewUrl}
                        onRemove={resetSingle}
                        removeLabel="Remove"
                    />
                ) : (
                    <SampleRow onPick={loadSample} disabled={singleUpload.isReading} />
                )}
            </div>
        </Dropzone>
    );

    const bulkPanel = (
        <div className="flex flex-col gap-4">
            <Dropzone
                id="bulk-file"
                multiple
                label={bulkFiles.length > 0 ? 'Drop more images here' : 'Drop up to 20 images here'}
                browseLabel={bulkFiles.length > 0 ? 'Add more images' : 'Choose images'}
                constraints={bulkUpload.constraints}
                accept={bulkUpload.accept}
                state={bulkUpload.state}
                reason={bulkUpload.error}
                onFiles={handleBulkFiles}
                disabled={bulkResize.isProcessing}
            />

            {bulkResize.isProcessing ? (
                <ul className="flex flex-col divide-y divide-line rounded-panel border border-line bg-surface-raised">
                    {bulkProgressRows.map((row) => (
                        <li key={row.id} className="flex items-baseline justify-between gap-4 px-4 py-2.5">
                            <span className="min-w-0 flex-1 truncate text-ui text-ink" title={row.name}>
                                {row.name}
                            </span>
                            <span className="shrink-0 font-data text-micro text-ink-muted">
                                {bulkStatusLabel(row)}
                            </span>
                        </li>
                    ))}
                </ul>
            ) : null}

            {!bulkResize.isProcessing && bulkFailures.length > 0 ? (
                <div className="rounded-panel border border-line bg-surface-sunken p-4">
                    <p className="text-ui text-ink">
                        {bulkFailures.length === 1
                            ? 'One image was left out:'
                            : `${bulkFailures.length} images were left out:`}
                    </p>
                    <ul className="mt-2 flex flex-col gap-1">
                        {bulkFailures.map((row) => (
                            <li key={row.id} className="flex items-baseline justify-between gap-4">
                                <span className="min-w-0 flex-1 truncate font-data text-micro text-ink-muted" title={row.name}>
                                    {row.name}
                                </span>
                                <span className="shrink-0 text-micro text-ink-muted">{row.error}</span>
                            </li>
                        ))}
                    </ul>
                </div>
            ) : null}

            {bulkFiles.length > 0 ? (
                <ul className="grid gap-2 md:grid-cols-2">
                    {bulkFiles.map((entry) => {
                        const target = entry.config ?? batchTarget;
                        return (
                            <li key={entry.id}>
                                <FilePreviewCard
                                    name={entry.name}
                                    size={entry.size}
                                    format={entry.format}
                                    width={entry.width}
                                    height={entry.height}
                                    previewUrl={entry.previewUrl}
                                    selected={entry.selected}
                                    onToggleSelected={(checked) => bulkUpload.updateFile(entry.id, { selected: checked })}
                                    onRemove={() => bulkUpload.removeFile(entry.id)}
                                    removeLabel="Remove"
                                    meta={(
                                        <p className="font-data text-micro text-ink-muted">
                                            <span aria-hidden="true">→ </span>
                                            {describeTarget(entry, target)}
                                            {entry.config ? (
                                                <>
                                                    {' · '}
                                                    <button
                                                        type="button"
                                                        onClick={() => bulkUpload.updateFile(entry.id, { config: null })}
                                                        className="rounded-input text-accent underline underline-offset-2"
                                                    >
                                                        unpin
                                                    </button>
                                                </>
                                            ) : null}
                                        </p>
                                    )}
                                />
                            </li>
                        );
                    })}
                </ul>
            ) : null}
        </div>
    );

    const singleAction = (
        <ToolAction
            label="Resize image"
            processingLabel="Resizing"
            isProcessing={singleSubmit.isProcessing}
            progress={singleSubmit.progress}
            disabled={!source || singleUpload.isReading}
            onClick={handleSingleSubmit}
            onCancel={singleSubmit.cancel}
            hint={source ? undefined : 'Add an image to turn this on.'}
        />
    );

    const bulkAction = (
        <ToolAction
            label={selected.length === 1 ? 'Resize 1 image' : `Resize ${selected.length} images`}
            processingLabel="Resizing"
            isProcessing={bulkResize.isProcessing}
            progress={bulkResize.progress}
            disabled={selected.length === 0 || bulkUpload.isReading}
            onClick={handleBulkSubmit}
            onCancel={bulkResize.cancel}
            hint={bulkFiles.length === 0 ? 'Add images to turn this on.' : undefined}
        />
    );

    let result = null;

    if (isSingle && singleResult) {
        result = (
            <ResultPanel
                variant="single"
                previewUrl={resultUrl}
                alt={`Resized copy of ${source?.name ?? 'your image'}`}
                filename={singleResult.filename}
                originalBytes={singleResult.originalBytes}
                resultBytes={singleResult.resultBytes}
                width={resultSize?.width}
                height={resultSize?.height}
                downloadLabel="Download image"
                onDownload={() => singleSubmit.download()}
                onReset={resetSingle}
                footnote="EXIF and GPS metadata are stripped from every output."
            />
        );
    } else if (!isSingle && bulkResize.result) {
        const failCount = bulkResize.result.failures.length;
        const failNote = failCount > 0
            ? ` ${failCount === 1 ? 'One image' : `${failCount} images`} could not be resized and ${failCount === 1 ? 'was' : 'were'} left out.`
            : '';

        result = (
            <ResultPanel
                variant="batch"
                rows={bulkResize.result.rows}
                downloadLabel="Download all as ZIP"
                onDownload={() => bulkResize.download()}
                onReset={resetBulk}
                footnote={`One ZIP, one file per image. EXIF and GPS metadata are stripped from every output.${failNote}`}
            />
        );
    }

    return (
        <ToolShell
            slug="resize"
            title={title}
            intro={intro}
            breadcrumb={breadcrumb}
            settingsLabel="Resize settings"
            settings={settings}
            panel={isSingle ? singlePanel : bulkPanel}
            error={formError ?? activeError}
            action={isSingle ? singleAction : bulkAction}
            result={result}
        >
            {children}
        </ToolShell>
    );
}
