'use client';

/**
 * The resize workspace: one image, or up to twenty.
 *
 * Lifted out of the 1334-line homepage monolith, where it also carried the
 * nav, the footer, the reviews and two modals, and where the single and bulk
 * panels shared one `isDragging` and one `errorMsg` — so dragging over one
 * zone lit up the other and an error raised in one tab appeared in both. The
 * two panels now own separate upload hooks, which is what actually fixes that.
 *
 * Both hooks are mounted at all times even though only one panel renders:
 * switching tabs must not silently throw away a batch someone just queued up.
 */
import { useCallback, useEffect, useMemo, useState } from 'react';

import ResultPanel from '@/components/tools/ResultPanel';
import ToolShell, { ToolAction } from '@/components/tools/ToolShell';
import Dropzone from '@/components/ui/Dropzone';
import FilePreviewCard from '@/components/ui/FilePreviewCard';
import {
    ALLOWED_OUTPUT_FORMATS,
    MAX_BULK_FILES,
    MAX_DIMENSION,
    MAX_SCALE_PERCENT,
    RESIZE_INPUT_FORMATS,
} from '@/lib/constants';
import { formatLabel } from '@/lib/hooks/upload-helpers';
import { useImageUpload } from '@/lib/hooks/useImageUpload';
import { useToolSubmit } from '@/lib/hooks/useToolSubmit';
import { parsePositiveInt, parseScale } from '@/lib/image/dimensions';
import { takePendingFiles } from '@/lib/pending-files';
import { readZipEntries } from '@/lib/zip-entries';

import { BulkSettings, SingleSettings } from './ResizeSettings';

/**
 * Bundled images so a visitor can see what comes out before handing over a
 * photo of their own. Generated by scripts/generate-samples.js — three aspect
 * ratios, because respecting one is the first thing a resizer has to prove.
 */
const SAMPLES = [
    { src: '/samples/landscape-1600x1067.jpg', name: 'landscape-1600x1067.jpg', label: 'Landscape', dimensions: '1600×1067' },
    { src: '/samples/portrait-1080x1440.jpg', name: 'portrait-1080x1440.jpg', label: 'Portrait', dimensions: '1080×1440' },
    { src: '/samples/square-1200x1200.jpg', name: 'square-1200x1200.jpg', label: 'Square', dimensions: '1200×1200' },
];

const DIMENSION_ERROR = `Width and height have to be whole numbers of pixels, up to ${MAX_DIMENSION}.`;
const SCALE_ERROR = `Scale has to be a number above 0 and no more than ${MAX_SCALE_PERCENT}.`;

function numberOrNull(value) {
    const parsed = Number(value);
    return Number.isFinite(parsed) && parsed > 0 ? Math.round(parsed) : null;
}

/**
 * 'original' is a UI convenience, not a server format: /api/resize only
 * encodes JPEG, PNG and WebP, so a GIF source resolves to JPEG here rather
 * than being silently rewritten by the route's fallback.
 */
function resolveOutputFormat(choice, sourceFormat) {
    if (choice && choice !== 'original') return choice;
    return ALLOWED_OUTPUT_FORMATS.includes(sourceFormat) ? sourceFormat : 'jpeg';
}

/** The same strict parsers the route uses, so the client and the server agree. */
function validateTarget(width, height, { requireOne = false } = {}) {
    const parsedWidth = parsePositiveInt(width, { max: MAX_DIMENSION });
    const parsedHeight = parsePositiveInt(height, { max: MAX_DIMENSION });

    if ((!parsedWidth.ok && !parsedWidth.absent) || (!parsedHeight.ok && !parsedHeight.absent)) {
        return { error: DIMENSION_ERROR };
    }
    if (requireOne && parsedWidth.absent && parsedHeight.absent) {
        return { error: 'Enter a width, a height, or both — or switch to Percent.' };
    }

    return {
        width: parsedWidth.ok ? parsedWidth.value : null,
        height: parsedHeight.ok ? parsedHeight.value : null,
    };
}

function describeTarget(entry, target) {
    const format = formatLabel(resolveOutputFormat(target.format, entry.format));

    if (target.width && target.height) return `${target.width}×${target.height} · ${format}`;
    if (target.width) return `${target.width}×auto · ${format}`;
    if (target.height) return `auto×${target.height} · ${format}`;
    if (Number.isFinite(entry.width) && Number.isFinite(entry.height)) {
        return `${entry.width}×${entry.height} · ${format}`;
    }
    return `Unchanged size · ${format}`;
}

function SampleRow({ onPick, disabled }) {
    return (
        <div className="flex flex-col items-center gap-2">
            <p className="text-micro text-ink-muted">No image to hand? Try one of these.</p>
            <div className="flex flex-wrap justify-center gap-2">
                {SAMPLES.map((sample) => (
                    <button
                        key={sample.src}
                        type="button"
                        disabled={disabled}
                        onClick={() => onPick(sample)}
                        className="flex items-baseline gap-2 rounded-button border border-line bg-surface-raised px-3 py-1.5 transition-colors duration-120 ease-snap hover:bg-surface-sunken disabled:opacity-60"
                    >
                        <span className="text-ui text-ink">{sample.label}</span>
                        <span className="font-data text-micro text-ink-muted">{sample.dimensions}</span>
                    </button>
                ))}
            </div>
        </div>
    );
}

export default function ResizeTool({
    title = 'Resize an Image Online',
    intro = 'Exact pixels, a percentage, or a platform size — then drop your file.',
    breadcrumb,
    children,
}) {
    const [mode, setMode] = useState('single');
    const [formError, setFormError] = useState(null);

    // Single
    const [sizeMode, setSizeMode] = useState('pixels');
    const [presetId, setPresetId] = useState(null);
    const [width, setWidth] = useState('');
    const [height, setHeight] = useState('');
    const [lockRatio, setLockRatio] = useState(true);
    const [scale, setScale] = useState('50');
    const [format, setFormat] = useState('original');
    const [resultUrl, setResultUrl] = useState(null);
    const [resultSize, setResultSize] = useState(null);

    // Bulk
    const [bulkWidth, setBulkWidth] = useState('');
    const [bulkHeight, setBulkHeight] = useState('');
    const [bulkFormat, setBulkFormat] = useState('original');
    const [bulkRows, setBulkRows] = useState(null);
    const [bulkOriginalBytes, setBulkOriginalBytes] = useState(0);

    const singleUpload = useImageUpload({ accept: RESIZE_INPUT_FORMATS });
    const bulkUpload = useImageUpload({
        accept: RESIZE_INPUT_FORMATS,
        multiple: true,
        maxFiles: MAX_BULK_FILES,
    });

    const singleSubmit = useToolSubmit({ endpoint: '/api/resize' });
    const bulkSubmit = useToolSubmit({ endpoint: '/api/resize-bulk' });

    const source = singleUpload.file;
    const ratio = source?.width && source?.height ? source.height / source.width : null;

    /* ---------------------------------------------------------------- *
     * Single
     * ---------------------------------------------------------------- */

    // The hook results are in the dependency arrays below as whole objects,
    // which is what exhaustive-deps demands for a `hook.method()` call. Their
    // members are all useCallback-stable, so the only cost is that a handler
    // is re-created each render — never a re-run of anything expensive.
    const handleSingleFiles = useCallback(async (files) => {
        setFormError(null);
        singleSubmit.reset();

        const [entry] = await singleUpload.selectFiles(files);
        if (!entry) return;

        // A preset already chosen is an explicit target; only an unconfigured
        // panel adopts the source dimensions.
        if (!presetId) {
            setWidth(entry.width ? String(entry.width) : '');
            setHeight(entry.height ? String(entry.height) : '');
        }
    }, [presetId, singleSubmit, singleUpload]);

    // The homepage hero takes the first drop and hands the file over as the
    // router transitions, so /resize opens with it already loaded. Empty on a
    // direct visit, and emptied by the read, so it cannot fire twice.
    useEffect(() => {
        const handed = takePendingFiles();
        if (handed.length > 0) void handleSingleFiles(handed);
    }, [handleSingleFiles]);

    // /resize#bulk is the registry href for the bulk tool, so the anchor has
    // to actually open that panel — on first paint, and again if someone
    // follows the link while already on this page, which does not remount.
    useEffect(() => {
        const sync = () => {
            if (window.location.hash === '#bulk') setMode('bulk');
        };

        sync();
        window.addEventListener('hashchange', sync);
        return () => window.removeEventListener('hashchange', sync);
    }, []);

    const singleResult = singleSubmit.result;

    // The output is measured, not predicted: with both sides set the route
    // scales to fill and trims, so a calculated number could be a lie.
    useEffect(() => {
        const blob = singleResult?.blob;
        if (!blob) {
            setResultUrl(null);
            setResultSize(null);
            return undefined;
        }

        const url = URL.createObjectURL(blob);
        setResultUrl(url);
        setResultSize(null);

        let cancelled = false;
        const probe = new window.Image();
        probe.onload = () => {
            if (!cancelled) setResultSize({ width: probe.naturalWidth, height: probe.naturalHeight });
        };
        probe.src = url;

        return () => {
            cancelled = true;
            URL.revokeObjectURL(url);
        };
    }, [singleResult]);

    const handleWidthChange = useCallback((value) => {
        setPresetId(null);
        setWidth(value);
        if (!lockRatio || !ratio) return;
        const next = numberOrNull(value);
        setHeight(next ? String(Math.max(1, Math.round(next * ratio))) : '');
    }, [lockRatio, ratio]);

    const handleHeightChange = useCallback((value) => {
        setPresetId(null);
        setHeight(value);
        if (!lockRatio || !ratio) return;
        const next = numberOrNull(value);
        setWidth(next ? String(Math.max(1, Math.round(next / ratio))) : '');
    }, [lockRatio, ratio]);

    const handlePresetSelect = useCallback((preset) => {
        if (!preset) {
            setPresetId(null);
            setWidth(source?.width ? String(source.width) : '');
            setHeight(source?.height ? String(source.height) : '');
            return;
        }

        setPresetId(preset.id);
        setSizeMode('pixels');
        // A platform size fixes both sides, so the ratio lock would immediately
        // overwrite one of them.
        setLockRatio(false);
        setWidth(String(preset.width));
        setHeight(String(preset.height));
    }, [source]);

    const loadSample = useCallback(async (sample) => {
        try {
            const response = await fetch(sample.src);
            if (!response.ok) throw new Error('sample unavailable');
            const blob = await response.blob();
            await handleSingleFiles([new File([blob], sample.name, { type: 'image/jpeg' })]);
        } catch {
            singleUpload.setError('That sample could not be loaded. Try again, or pick a file of your own.');
        }
    }, [handleSingleFiles, singleUpload]);

    const handleSingleSubmit = useCallback(async () => {
        if (!source) {
            setFormError('Choose an image first.');
            return;
        }

        const formData = new FormData();
        formData.append('file', source.file);
        formData.append('format', resolveOutputFormat(format, source.format));

        if (sizeMode === 'pixels') {
            const target = validateTarget(width, height, { requireOne: true });
            if (target.error) {
                setFormError(target.error);
                return;
            }
            if (target.width) formData.append('width', String(target.width));
            if (target.height) formData.append('height', String(target.height));
        } else {
            const parsed = parseScale(scale);
            if (!parsed.ok) {
                setFormError(SCALE_ERROR);
                return;
            }
            formData.append('scale', String(parsed.value));
        }

        setFormError(null);
        await singleSubmit.submit(formData, { originalBytes: source.size });
    }, [format, height, scale, singleSubmit, sizeMode, source, width]);

    const resetSingle = useCallback(() => {
        singleSubmit.reset();
        singleUpload.clear();
        setPresetId(null);
        setWidth('');
        setHeight('');
        setFormError(null);
    }, [singleSubmit, singleUpload]);

    const outputPreview = useMemo(() => {
        if (!source?.width || !source?.height) return null;

        if (sizeMode === 'percent') {
            const percent = Number(scale);
            if (!Number.isFinite(percent) || percent <= 0) return null;
            return `${Math.max(1, Math.round(source.width * (percent / 100)))}×${Math.max(1, Math.round(source.height * (percent / 100)))} px`;
        }

        const targetWidth = numberOrNull(width);
        const targetHeight = numberOrNull(height);

        if (targetWidth && targetHeight) return `${targetWidth}×${targetHeight} px`;
        if (targetWidth) return `${targetWidth}×${Math.max(1, Math.round((source.height / source.width) * targetWidth))} px`;
        if (targetHeight) return `${Math.max(1, Math.round((source.width / source.height) * targetHeight))}×${targetHeight} px`;
        return null;
    }, [height, scale, sizeMode, source, width]);

    /* ---------------------------------------------------------------- *
     * Bulk
     * ---------------------------------------------------------------- */

    const bulkFiles = bulkUpload.files;
    const selected = useMemo(() => bulkFiles.filter((entry) => entry.selected), [bulkFiles]);
    const allSelected = bulkFiles.length > 0 && selected.length === bulkFiles.length;

    const batchTarget = useMemo(() => ({
        width: numberOrNull(bulkWidth),
        height: numberOrNull(bulkHeight),
        format: bulkFormat,
    }), [bulkFormat, bulkHeight, bulkWidth]);

    const handleBulkFiles = useCallback(async (files) => {
        setFormError(null);
        setBulkRows(null);
        bulkSubmit.reset();
        await bulkUpload.selectFiles(files);
    }, [bulkSubmit, bulkUpload]);

    const handleToggleAll = useCallback(() => {
        const next = !allSelected;
        for (const entry of bulkFiles) bulkUpload.updateFile(entry.id, { selected: next });
    }, [allSelected, bulkFiles, bulkUpload]);

    const handleApplyToSelected = useCallback(() => {
        const target = validateTarget(bulkWidth, bulkHeight);
        if (target.error) {
            setFormError(target.error);
            return;
        }

        setFormError(null);
        for (const entry of bulkFiles) {
            if (!entry.selected) continue;
            bulkUpload.updateFile(entry.id, {
                config: { width: target.width, height: target.height, format: bulkFormat },
            });
        }
    }, [bulkFiles, bulkFormat, bulkHeight, bulkUpload, bulkWidth]);

    const handleBulkSubmit = useCallback(async () => {
        const included = bulkFiles.filter((entry) => entry.selected);

        if (included.length === 0) {
            setFormError('Tick at least one image to resize.');
            return;
        }

        const fallback = validateTarget(bulkWidth, bulkHeight);
        if (fallback.error) {
            setFormError(fallback.error);
            return;
        }

        setFormError(null);
        setBulkRows(null);

        const formData = new FormData();
        let originalBytes = 0;

        included.forEach((entry, index) => {
            const target = entry.config ?? { ...fallback, format: bulkFormat };
            formData.append(`file_${index}`, entry.file);
            formData.append(`config_${index}`, JSON.stringify({
                width: target.width ?? null,
                height: target.height ?? null,
                format: target.format ?? 'original',
            }));
            originalBytes += entry.size;
        });

        setBulkOriginalBytes(originalBytes);

        const result = await bulkSubmit.submit(formData, { originalBytes });
        if (!result) return;

        // The ZIP states each output's size in its own index, so the per-file
        // rows are read from the archive rather than guessed at.
        try {
            const entries = readZipEntries(await result.blob.arrayBuffer());
            if (entries.length === included.length) {
                setBulkRows(included.map((entry, index) => ({
                    id: entry.id,
                    name: entry.name,
                    originalBytes: entry.size,
                    resultBytes: entries[index].size,
                })));
            }
        } catch {
            // Unreadable archive: the totals panel below still prints real
            // numbers, so the visitor never sees a fabricated per-file figure.
        }
    }, [bulkFiles, bulkFormat, bulkHeight, bulkSubmit, bulkWidth]);

    const resetBulk = useCallback(() => {
        bulkSubmit.reset();
        bulkUpload.clear();
        setBulkRows(null);
        setFormError(null);
    }, [bulkSubmit, bulkUpload]);

    /* ---------------------------------------------------------------- *
     * Render
     * ---------------------------------------------------------------- */

    const isSingle = mode === 'single';
    const activeSubmit = isSingle ? singleSubmit : bulkSubmit;

    const changeMode = useCallback((next) => {
        setMode(next);
        setFormError(null);
    }, []);

    const settings = (
        <>
            {isSingle ? (
                <SingleSettings
                    mode={mode}
                    onModeChange={changeMode}
                    sizeMode={sizeMode}
                    onSizeModeChange={setSizeMode}
                    presetId={presetId}
                    onPresetSelect={handlePresetSelect}
                    width={width}
                    height={height}
                    onWidthChange={handleWidthChange}
                    onHeightChange={handleHeightChange}
                    lockRatio={lockRatio}
                    onLockRatioChange={setLockRatio}
                    scale={scale}
                    onScaleChange={setScale}
                    format={format}
                    onFormatChange={setFormat}
                    sourceFormat={source?.format ?? null}
                    outputPreview={outputPreview}
                />
            ) : (
                <BulkSettings
                    mode={mode}
                    onModeChange={changeMode}
                    width={bulkWidth}
                    height={bulkHeight}
                    onWidthChange={setBulkWidth}
                    onHeightChange={setBulkHeight}
                    format={bulkFormat}
                    onFormatChange={setBulkFormat}
                    selectedCount={selected.length}
                    totalCount={bulkFiles.length}
                    allSelected={allSelected}
                    onToggleAll={handleToggleAll}
                    onApplyToSelected={handleApplyToSelected}
                />
            )}
        </>
    );

    const singlePanel = (
        <Dropzone
            id="resize-file"
            label={source ? 'Drop another image to replace this one' : 'Drop an image here'}
            browseLabel={source ? 'Replace image' : 'Choose an image'}
            constraints={singleUpload.constraints}
            accept={singleUpload.accept}
            state={singleUpload.state}
            reason={singleUpload.error}
            onFiles={handleSingleFiles}
            disabled={singleSubmit.isProcessing}
        >
            <div className="w-full max-w-lg">
                {source ? (
                    <FilePreviewCard
                        name={source.name}
                        size={source.size}
                        format={source.format}
                        width={source.width}
                        height={source.height}
                        previewUrl={source.previewUrl}
                        onRemove={resetSingle}
                        removeLabel="Remove"
                    />
                ) : (
                    <SampleRow onPick={loadSample} disabled={singleUpload.isReading} />
                )}
            </div>
        </Dropzone>
    );

    const bulkPanel = (
        <div className="flex flex-col gap-4">
            <Dropzone
                id="bulk-file"
                multiple
                label={bulkFiles.length > 0 ? 'Drop more images here' : 'Drop up to 20 images here'}
                browseLabel={bulkFiles.length > 0 ? 'Add more images' : 'Choose images'}
                constraints={bulkUpload.constraints}
                accept={bulkUpload.accept}
                state={bulkUpload.state}
                reason={bulkUpload.error}
                onFiles={handleBulkFiles}
                disabled={bulkSubmit.isProcessing}
            />

            {bulkFiles.length > 0 ? (
                <ul className="grid gap-2 md:grid-cols-2">
                    {bulkFiles.map((entry) => {
                        const target = entry.config ?? batchTarget;
                        return (
                            <li key={entry.id}>
                                <FilePreviewCard
                                    name={entry.name}
                                    size={entry.size}
                                    format={entry.format}
                                    width={entry.width}
                                    height={entry.height}
                                    previewUrl={entry.previewUrl}
                                    selected={entry.selected}
                                    onToggleSelected={(checked) => bulkUpload.updateFile(entry.id, { selected: checked })}
                                    onRemove={() => {
                                        setBulkRows(null);
                                        bulkUpload.removeFile(entry.id);
                                    }}
                                    removeLabel="Remove"
                                    meta={(
                                        <p className="font-data text-micro text-ink-muted">
                                            <span aria-hidden="true">→ </span>
                                            {describeTarget(entry, target)}
                                            {entry.config ? (
                                                <>
                                                    {' · '}
                                                    <button
                                                        type="button"
                                                        onClick={() => bulkUpload.updateFile(entry.id, { config: null })}
                                                        className="rounded-input text-accent underline underline-offset-2"
                                                    >
                                                        unpin
                                                    </button>
                                                </>
                                            ) : null}
                                        </p>
                                    )}
                                />
                            </li>
                        );
                    })}
                </ul>
            ) : null}
        </div>
    );

    const singleAction = (
        <ToolAction
            label="Resize image"
            processingLabel="Resizing"
            isProcessing={singleSubmit.isProcessing}
            progress={singleSubmit.progress}
            disabled={!source || singleUpload.isReading}
            onClick={handleSingleSubmit}
            onCancel={singleSubmit.cancel}
            hint={source ? undefined : 'Add an image to turn this on.'}
        />
    );

    const bulkAction = (
        <ToolAction
            label={selected.length === 1 ? 'Resize 1 image' : `Resize ${selected.length} images`}
            processingLabel="Resizing"
            isProcessing={bulkSubmit.isProcessing}
            progress={bulkSubmit.progress}
            disabled={selected.length === 0 || bulkUpload.isReading}
            onClick={handleBulkSubmit}
            onCancel={bulkSubmit.cancel}
            hint={bulkFiles.length === 0 ? 'Add images to turn this on.' : undefined}
        />
    );

    let result = null;

    if (isSingle && singleResult) {
        result = (
            <ResultPanel
                variant="single"
                previewUrl={resultUrl}
                alt={`Resized copy of ${source?.name ?? 'your image'}`}
                filename={singleResult.filename}
                originalBytes={singleResult.originalBytes}
                resultBytes={singleResult.resultBytes}
                width={resultSize?.width}
                height={resultSize?.height}
                downloadLabel="Download image"
                onDownload={() => singleSubmit.download()}
                onReset={resetSingle}
                footnote="EXIF and GPS metadata are stripped from every output."
            />
        );
    } else if (!isSingle && bulkSubmit.result) {
        result = bulkRows ? (
            <ResultPanel
                variant="batch"
                rows={bulkRows}
                downloadLabel="Download all as ZIP"
                onDownload={() => bulkSubmit.download()}
                onReset={resetBulk}
                footnote="One ZIP, one file per image. EXIF and GPS metadata are stripped from every output."
            />
        ) : (
            <ResultPanel
                variant="single"
                filename={bulkSubmit.result.filename}
                originalBytes={bulkOriginalBytes}
                resultBytes={bulkSubmit.result.resultBytes}
                downloadLabel="Download all as ZIP"
                onDownload={() => bulkSubmit.download()}
                onReset={resetBulk}
                footnote="Measured against the ZIP, which is compressed once more on top of the images."
            />
        );
    }

    return (
        <ToolShell
            slug="resize"
            title={title}
            intro={intro}
            breadcrumb={breadcrumb}
            settingsLabel="Resize settings"
            settings={settings}
            panel={isSingle ? singlePanel : bulkPanel}
            error={formError ?? activeSubmit.error}
            action={isSingle ? singleAction : bulkAction}
            result={result}
        >
            {children}
        </ToolShell>
    );
}
